### ISSUE TITLE
Could jattach enable remote debug dynamically?

### ISSUE THREAD

**Issue by robberphex** [jattach/jattach#70]
Is there any way to enable Java remote debug, with out re-launch Java application?

I saw that `libjdwp.so` has  `Agent_OnLoad`, and haven't `Agent_OnAttach`. Could we add `Agent_OnAttach` to supoort?

**Comment by apangin** [comment]
jdwp agent requires certain [JVM TI Capabilities](https://docs.oracle.com/en/java/javase/11/docs/specs/jvmti.html#capability) that can be added only at JVM startup. It cannot be loaded dynamically at runtime.

**Comment by robberphex** [comment]
Here is the capabilities that jdwp needed:
https://github.com/adoptium/jdk8u/blob/338acde33061b8af9d30aa510d86ec8156009021/jdk/src/share/back/debugInit.c#L309-L321
```
/* Fill in ones that we must have */
    (void)memset(&needed_capabilities,0,sizeof(needed_capabilities));
    needed_capabilities.can_access_local_variables              = 1;
    needed_capabilities.can_generate_single_step_events         = 1;
    needed_capabilities.can_generate_exception_events           = 1;
    needed_capabilities.can_generate_frame_pop_events           = 1;
    needed_capabilities.can_generate_breakpoint_events          = 1;
    needed_capabilities.can_suspend                             = 1;
    needed_capabilities.can_generate_method_entry_events        = 1;
    needed_capabilities.can_generate_method_exit_events         = 1;
    needed_capabilities.can_generate_garbage_collection_events  = 1;
    needed_capabilities.can_maintain_original_method_order      = 1;
    needed_capabilities.can_generate_monitor_events             = 1;
    needed_capabilities.can_tag_objects                         = 1;
```
It seems that those capabilities could be added dynamically.

**Comment by apangin** [comment]
`can_access_local_variables`, `can_generate_single_step_events`, `can_generate_exception_events`, `can_generate_frame_pop_events`, `can_maintain_original_method_order`, `can_generate_method_{entry,exit}_events` and `can_generate_breakpoint_events` can be added only in OnLoad phase, i.e. only at JVM startup.

Anyway, this is out of scope of jattach project. You can use [serviceability-dev](https://mail.openjdk.org/mailman/listinfo/serviceability-dev) mailing list for the discussion of jdwp capabilities.
