### ISSUE TITLE
why load command need double read in jattach_hotspot.c?

### ISSUE THREAD

**Issue by sustbeckham** [jattach/jattach#76]
```
if (result == 0 && argc > 0 && strcmp(argv[0], "load") == 0) { 
        size_t total = bytes;
        while (total < sizeof(buf) - 1 && (bytes = read(fd, buf + total, sizeof(buf) - 1 - total)) > 0) {
            total += (size_t)bytes;
            printf("xxxx");
        }
        bytes = total;
 }
```
I try to add printf in while condition and rebuild,  but no message print. 

```
jattach 1007 load xxx.so true
Connected to remote JVM
JVM response code = 0
return code: 0
```

So why do we need to read this again? thanks.

**Comment by apangin** [comment]
None of socket read calls is guaranteed to receive all data from the remote JVM. A canonical way to handle incoming socket data is to call read/recv in a loop until it returns EOF or error.

**Comment by sustbeckham** [comment]
thanks and close. :)
