### ISSUE TITLE
Support for jmap -live

### ISSUE THREAD

**Issue by colathurv** [jattach/jattach#78]
I would like to know if jattach supports the equivalent of the jmap -dump:live as mentioned in Oracle documentation. The intent here is to only dump live objects, in order to optimize the size of the dump file. Since jattach only has the dumpheap option, it is not clear, if the live option is supported. 

Appreciate your help.

**Comment by apangin** [comment]
Yes, just add `-live` option at the end:
```
jattach PID dumpheap outputfile.hprof -live
```
