### ISSUE TITLE
load agent just supports a maximum of 300 characters in windows

### ISSUE THREAD

**Issue by touyudexiaomao** [jattach/jattach#80]
I tested the release version(v2.2) on Windows with my JDK version is :

- java version "1.8.0_391"
- Java(TM) SE Runtime Environment (build 1.8.0_391-b13)
- Java HotSpot(TM) 64-Bit Server VM (build 25.391-b13, mixed mode)

I found that the command 'jattach.exe 1432 load instrument false agent.jar=agentAgrs' just supports a maximum of 300 characters.
If exceeded, it will be truncated. So I lost some of the parameters passed to the agent.

For example:
I input like this:
**jattach.exe 1432 load instrument false "C:\Windows\TEMP\uhs_jar\agentLoad-1.0.jar=serviceJarPath=D:\mytest123_HSCA_Agent\curator\java\dumpClassFile-1.0.jar;serviceEntryClassName=com.mytest123net.uhs.AddTransformer;exportDir=C:\ProgramData\mytest123\mytest123_UHS_Agent\data\resultsa\mytest123ExportPath;Pid=1432"**

However, the parameters received by the agent is:
**serviceJarPath=D:\mytest123_HSCA_Agent\curator\java\dumpClassFile-1.0.jar;serviceEntryClassName=com.mytest123net.uhs.AddTransformer;exportDir=C:\ProgramData\mytest123\mytest123_UHS_Agent\data\resultsa\mytest123ExportP**

It lost the following characters：“**ath;Pid=1432**”

I don't understand why this is happening.
Looking forward to your reply.

**Comment by apangin** [comment]
Thank you for the report.
On Windows, the length of each jattach argument is limited to `MAX_PATH` characters, which is equal to 260:
https://github.com/jattach/jattach/blob/10cd6c396655a1708fe216f65ac71547af38025c/src/windows/jattach.c#L21

We will shift the limit up in the next version of jattach.

**Comment by touyudexiaomao** [comment]
I found that there is also in Linux with a length limit of 1024.

**Comment by touyudexiaomao** [comment]
I got it. Thanks.

**Comment by apangin** [comment]
The fix has been pushed; closing the issue.
